# Generated by Django 4.2.4 on 2023-08-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_alter_advertisement_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
